spring:
  jpa:
    hibernate:
      # 多数据源下，该属性不生效，需要在配置中额外指定，这里仅表示普通定义
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    show-sql: true
  # 定义不同数据源的连接信息
  datasource:
      url: jdbc:postgresql://localhost:5432/graphql_demo
      username: dbadmin
      password: dl123
#      driver-class-name: org.postgresql.Driver
#      hikari:
#        maximum-pool-size: 2
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        driver-class-name: org.postgresql.Driver
        username: dbadmin
        password: dl123
        initial-size: 2
        min-idle: 1
        max-active: 2
        max-wait: 5000
        time-between-connect-error-millis: 60000
        stat-view-servlet:
          url-pattern: "/druid/*"
          reset-enable: false
            # 登录名
          login-username: admin
          # 登录密码
          login-password: 123456
        web-stat-filter:
          enabled: true
          url-pattern: "/*"
          exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"



server:
  port: 8001
graphql:
  scan-path: cc.voox.demo